import test from 'node:test';
import assert from 'node:assert/strict';
import {startEmulator,api,profile} from './emulator-fixture.mjs';
test('regras reais: cadastro por RE, contexto móvel, escrita e consultas por cargo', {skip:!process.env.MSA_DATABASE_EMULATOR_JAR},async t=>{
 const e=await startEmulator(process.env.MSA_DATABASE_EMULATOR_JAR);t.after(e.close);
 const request=(...args)=>api(e.base,...args),ok=async(...args)=>{const r=await request(...args);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;},deny=async(...args)=>assert.equal((await request(...args)).status,401);
 const profiles={op:profile('operador'),op2:profile('operador','montagem','ABF-02'),sup:profile('supervisor'),chief:profile('chefe'),outside:profile('supervisor','injecao')};
 // Perfis em uso de versões anteriores. Novos cadastros começam sem contexto.
 for(const [uid,p]of Object.entries(profiles))await ok('perfis/'+uid,'owner','PUT',p);
 await ok('perfis/newop','newop','PUT',profile('operador','',''));
 await ok('perfis/newsup','newsup','PUT',profile('supervisor','',''));
 await ok('perfis/newchief','newchief','PUT',profile('chefe','',''));
 await deny('perfis/op','op','PATCH',{cargo:'chefe'});
 await deny('perfis/op','sup','PATCH',{cargo:'chefe'});
 const machine={nome:'Montagem 01',setorId:'montagem',processo:'Montagem',produto:'Abafador',metaDiaria:100,parametros:{temperatura:{nome:'Temperatura',unidade:'°C',min:240,max:260}},createdAt:Date.now(),updatedAt:Date.now(),atualizadoPor:'sup'};
 await ok('setores/montagem','sup','PUT',{nome:'Montagem'});
 await ok('maquinas/ABF-01','sup','PUT',machine);await ok('maquinas/ABF-02','sup','PUT',{...machine,nome:'Montagem 02'});
 await ok('maquinas/SEL-01','chief','PUT',{...machine,nome:'Selagem 01',setorId:'selagem',atualizadoPor:'chief'});
 await ok('maquinas','newop');
 await ok('maquinas','newsup');
 await deny('perfis/newop','newop','PATCH',{setorId:'montagem',maquinaId:'SEL-01'});
 await deny('perfis/newop','newop','PATCH',{setorId:'selagem',maquinaId:'NAO-EXISTE'});
 await ok('perfis/newsup','newsup','PATCH',{setorId:'selagem'});
 await deny('maquinas/INJ-X','sup','PUT',{...machine,setorId:'injecao'});
 await ok('maquinas/ABF-01','chief','PATCH',{metaDiaria:200,updatedAt:Date.now(),atualizadoPor:'chief'});
 await deny('maquinas/ABF-01','chief','PATCH',{'parametros/temperatura/max':999});
 await deny('maquinas/ABF-01','chief','PATCH',{parametros:null});
 const record={setorId:'montagem',maquinaId:'ABF-01',usuarioId:'op',usuarioRe:'1',createdAt:Date.now(),updatedAt:Date.now(),atualizadoPor:'op',verificado:false,observacao:'',quantidade:80,inicio:Date.now()-3600000,fim:Date.now(),turno:'1',produto:'Abafador',lote:'OP-01'};
 await deny('registrosProducao/unassigned','newop','PUT',{...record,usuarioId:'newop',atualizadoPor:'newop'});
 await ok('registrosProducao/r1','op','PUT',record);
 await deny('registrosProducao/r2','op','PUT',{...record,maquinaId:'ABF-02'});
 await deny('registrosProducao/r1','op2','PATCH',{quantidade:999,atualizadoPor:'op2'});
 await deny('registrosProducao/r1','chief','PATCH',{quantidade:999,atualizadoPor:'chief'});
 await deny('registrosProducao','op');
 await ok('registrosProducao','op','GET',undefined,{orderBy:'maquinaId',equalTo:'ABF-01'});
 await deny('registrosProducao','op','GET',undefined,{orderBy:'maquinaId',equalTo:'ABF-02'});
 await ok('registrosProducao','sup','GET',undefined,{orderBy:'setorId',equalTo:'montagem'});
 await deny('registrosProducao','sup','GET',undefined,{orderBy:'setorId',equalTo:'injecao'});
 await ok('registrosProducao','chief');
 await deny('registrosProducao/r1','outside');
 await ok('registrosProducao/r1','sup','PATCH',{verificado:true,verificadoPor:'sup',verificadoEm:Date.now(),updatedAt:Date.now(),atualizadoPor:'sup'});
 await deny('registrosProducao/r1','sup','PATCH',{quantidade:999,atualizadoPor:'sup'});
 await deny('registrosProducao/r1','op','PATCH',{verificado:true,verificadoPor:'op'});
 // Correção do autor preserva origem e pede nova conferência.
 await ok('registrosProducao/r1','op','PUT',{...record,quantidade:90,updatedAt:Date.now()});
 const {quantidade,inicio,fim,turno,produto,lote,...common}=record;
 await ok('leituras/l1','op','PUT',{...common,data:Date.now(),lote:'OP-01',valores:{temperatura:255}});
 await ok('leituras/l1','sup','PATCH',{verificado:true,verificadoPor:'sup',verificadoEm:Date.now(),updatedAt:Date.now(),atualizadoPor:'sup'});
 await deny('leituras/l1','sup','PATCH',{'valores/temperatura':999});
 await deny('leituras/l1','sup','PATCH',{valores:null});
 await ok('paradas/p1','op','PUT',{...common,inicio:Date.now()-600000,fim:0,motivo:'Falha',causa:'',encerradaPor:''});
 await ok('paradas/p1','sup','PATCH',{fim:Date.now(),causa:'Ajuste',encerradaPor:'sup',updatedAt:Date.now(),atualizadoPor:'sup'});
 await ok('ocorrencias/o1','op','PUT',{...common,data:Date.now(),descricao:'Teste',prioridade:'alta',status:'aberta',resolucao:''});
 await deny('ocorrencias/o1','op','PATCH',{status:'resolvida',resolucao:'Teste'});
 await ok('ocorrencias/o1','sup','PATCH',{status:'resolvida',resolucao:'Ajuste concluído',updatedAt:Date.now(),atualizadoPor:'sup'});
 await ok('perdas/q1','op','PUT',{...common,tipo:'perda',quantidade:0.3,unidade:'kg',data:Date.now(),motivo:'Laminado',produto:'Selo',lote:'OP-01'});
 await deny('perdas/q2','op','PUT',{...common,tipo:'refugo',quantidade:0.3,unidade:'pecas',data:Date.now(),motivo:'Teste',produto:'Selo',lote:'OP-01'});
 await ok('consolidacoes/c1','sup','PUT',{setorId:'montagem',usuarioId:'sup',usuarioRe:'1',inicio:Date.now()-3600000,fim:Date.now(),observacao:'Resumo',createdAt:Date.now()});
 await deny('consolidacoes/c2','op','PUT',{setorId:'montagem',usuarioId:'op'});
 await ok('consolidacoes','chief');
 await ok('perfis/op','sup','PATCH',{maquinaId:'ABF-02'});
 await deny('registrosProducao/r3','op','PUT',record);
 await ok('registrosProducao/r3','op','PUT',{...record,maquinaId:'ABF-02'});
 await deny('perfis/op','outside','PATCH',{maquinaId:'INJ-01'});
 // Mesmo UID/RE muda de setor por iniciativa do funcionário; a origem não muda.
 await ok('perfis/op','op','PATCH',{setorId:'selagem',maquinaId:'SEL-01'});
 const moved=await ok('perfis/op','op');assert.equal(moved.re,'1');assert.equal(moved.cargo,'operador');
 await deny('registrosProducao/old-machine','op','PUT',record);
 await deny('registrosProducao','op','GET',undefined,{orderBy:'maquinaId',equalTo:'ABF-02'});
 await ok('registrosProducao/r4','op','PUT',{...record,setorId:'selagem',maquinaId:'SEL-01',lote:'OP-SEL'});
 const current=await ok('registrosProducao','op','GET',undefined,{orderBy:'maquinaId',equalTo:'SEL-01'});assert.deepEqual(Object.keys(current),['r4']);
 const historical=await ok('registrosProducao/r1','chief');assert.equal(historical.setorId,'montagem');assert.equal(historical.maquinaId,'ABF-01');assert.equal(historical.usuarioId,'op');
 await ok('perfis/sup','sup','PATCH',{setorId:'selagem'});
 const sector=await ok('registrosProducao','sup','GET',undefined,{orderBy:'setorId',equalTo:'selagem'});assert.equal(sector.r4.usuarioId,'op');
 await deny('registrosProducao','sup','GET',undefined,{orderBy:'setorId',equalTo:'montagem'});
 await deny('perfis/op','op','PATCH',{re:'2'});
 await deny('perfis/op','op','PATCH',{cargo:'chefe'});
});
